const CATEGORIES = [
  {id:'iron',uz:'Dazmollar',ru:'Утюги',en:'Irons'},
  {id:'vacuum',uz:'Changyutgichlar',ru:'Пылесосы',en:'Vacuum cleaners'},
  {id:'kitchen',uz:'Oshxona uchun',ru:'Для кухни',en:'Kitchen'},
  {id:'hair',uz:'Fenlar',ru:'Фены',en:'Hair dryers'},
  {id:'board',uz:'Dazmol doskalari',ru:'Гладильные доски',en:'Ironing boards'},
];

const SAMPLE_PRODUCTS = [
  {id:'sample-0',sample:true,category:'iron',brand:'Namuna',price:320000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/iron.png'],title:{uz:'Bug‘li dazmol',ru:'Паровой утюг',en:'Steam iron'},description:{uz:'Kundalik foydalanish uchun qulay bug‘li dazmol. Namuna mahsulot.',ru:'Удобный паровой утюг для ежедневного использования. Демонстрационный товар.',en:'Convenient steam iron for everyday use. Sample product.'}},
  {id:'sample-1',sample:true,category:'vacuum',brand:'Namuna',price:890000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/vacuum.png'],cardImage:'/assets/products/vacuum-card.png',title:{uz:'Konteynerli changyutgich',ru:'Контейнерный пылесос',en:'Canister vacuum cleaner'},description:{uz:'Bu namuna mahsulot. Rasm va narx faqat sayt ko‘rinishini ko‘rsatish uchun berilgan.',ru:'Это демонстрационный товар. Фото и цена указаны только для примера.',en:'This is a sample product. Image and price are shown for demonstration only.'}},
  {id:'sample-2',sample:true,category:'kitchen',brand:'Namuna',price:245000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/pot.png'],title:{uz:'Shisha qopqoqli qozon',ru:'Кастрюля со стеклянной крышкой',en:'Pot with glass lid'},description:{uz:'Oshxona uchun zanglamaydigan po‘lat qozon. Namuna mahsulot.',ru:'Кастрюля из нержавеющей стали для кухни. Демонстрационный товар.',en:'Stainless steel kitchen pot. Sample product.'}},
  {id:'sample-3',sample:true,category:'hair',brand:'Namuna',price:195000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/hairdryer.png'],title:{uz:'Kundalik foydalanish uchun fen',ru:'Фен для ежедневного использования',en:'Everyday hair dryer'},description:{uz:'Uyda kundalik foydalanish uchun fen. Namuna mahsulot.',ru:'Фен для ежедневного использования дома. Демонстрационный товар.',en:'Hair dryer for everyday home use. Sample product.'}},
  {id:'sample-4',sample:true,category:'board',brand:'Namuna',price:285000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/board.png'],title:{uz:'Yig‘iladigan dazmol doskasi',ru:'Складная гладильная доска',en:'Folding ironing board'},description:{uz:'Yig‘ib qo‘yish qulay bo‘lgan dazmol doskasi. Namuna mahsulot.',ru:'Удобная складная гладильная доска. Демонстрационный товар.',en:'Convenient folding ironing board. Sample product.'}},
  {id:'sample-5',sample:true,category:'kitchen',brand:'Namuna',price:210000,oldPrice:0,inStock:true,visible:true,images:['/assets/products/kettle.png'],title:{uz:'Shisha elektr choynak',ru:'Стеклянный электрочайник',en:'Glass electric kettle'},description:{uz:'Shisha korpusli elektr choynak. Namuna mahsulot.',ru:'Электрочайник со стеклянным корпусом. Демонстрационный товар.',en:'Electric kettle with glass body. Sample product.'}},
];

const DEFAULT_SETTINGS = {
  phone1:'+998 97 400 77 53', phone2:'+998 97 407 77 53', telegram:'Abdujabbor_shop',
  location:'Toshkent shahri', delivery:'Toshkent bo‘ylab yetkazib berish',
  deliveryNote:'Yetkazib berish narxi va muddatini buyurtma vaqtida kelishamiz.',
  about:{
    uz:'Abdujabbor Shop — maishiy texnika va uy-ro‘zg‘or buyumlari do‘koni. Dazmol, changyutgich, dazmol doskasi, qozon, fen va boshqa kundalik buyumlarni taklif qilamiz.',
    ru:'Abdujabbor Shop — магазин бытовой техники и товаров для дома. Предлагаем утюги, пылесосы, гладильные доски, посуду, фены и другие товары.',
    en:'Abdujabbor Shop is a home appliance and household goods store. We offer irons, vacuum cleaners, ironing boards, cookware, hair dryers and more.'
  }
};

const UI = {
  uz:{catalog:'Katalog',search:'Mahsulot qidirish...',about:'Biz haqimizda',contact:'Aloqa',question:'Savolingiz bormi?',heroEyebrow:'UYINGIZ UCHUN, MEHR BILAN',heroTitle:'Kichik qulayliklar.\nKatta farq.',heroText:'Uy yumushlarini yengillashtiradigan texnika va har kuni kerak bo‘ladigan buyumlar.',seeProducts:'Mahsulotlarni ko‘rish',help:'Tanlashda yordam beramiz',telegram:'Telegram kanalimiz',homeNeed:'Uy uchun keraklisi',all:'Barcha mahsulotlar',recommended:'Tavsiya etilgan',priceLow:'Narx: arzon',priceHigh:'Narx: qimmat',demo:'Namuna katalog: rasmlar va narxlar tanishish uchun. Haqiqiy mahsulotlar tez orada qo‘shiladi.',details:'Batafsil',contactUs:'Biz bilan bog‘laning',admin:'Admin panel',backCatalog:'Katalogga qaytish',askPrice:'Narx va mavjudligini aniqlashtiring',askTelegram:'Telegram orqali so‘rash',call:'Qo‘ng‘iroq qilish',delivery:'Toshkent bo‘ylab yetkazib berish',aboutProduct:'Mahsulot haqida',brand:'Brend',sample:'Namuna',out:'Sotuvda yo‘q'},
  ru:{catalog:'Каталог',search:'Поиск товара...',about:'О нас',contact:'Контакты',question:'Есть вопросы?',heroEyebrow:'ДЛЯ ВАШЕГО ДОМА, С ЗАБОТОЙ',heroTitle:'Маленькие удобства.\nБольшая разница.',heroText:'Техника и товары, которые делают домашние дела проще.',seeProducts:'Смотреть товары',help:'Поможем с выбором',telegram:'Наш Telegram',homeNeed:'Всё для дома',all:'Все товары',recommended:'Рекомендуемые',priceLow:'Сначала дешевле',priceHigh:'Сначала дороже',demo:'Демонстрационный каталог: изображения и цены приведены для ознакомления.',details:'Подробнее',contactUs:'Связаться с нами',admin:'Админ-панель',backCatalog:'Вернуться в каталог',askPrice:'Уточните цену и наличие',askTelegram:'Спросить в Telegram',call:'Позвонить',delivery:'Доставка по Ташкенту',aboutProduct:'О товаре',brand:'Бренд',sample:'Образец',out:'Нет в наличии'},
  en:{catalog:'Catalog',search:'Search products...',about:'About us',contact:'Contact',question:'Have a question?',heroEyebrow:'FOR YOUR HOME, WITH CARE',heroTitle:'Small comforts.\nBig difference.',heroText:'Appliances and everyday items that make home life easier.',seeProducts:'View products',help:'We help you choose',telegram:'Our Telegram',homeNeed:'Essentials for home',all:'All products',recommended:'Recommended',priceLow:'Price: low to high',priceHigh:'Price: high to low',demo:'Sample catalog: images and prices are for demonstration. Real products will be added soon.',details:'Details',contactUs:'Contact us',admin:'Admin panel',backCatalog:'Back to catalog',askPrice:'Confirm price and availability',askTelegram:'Ask on Telegram',call:'Call',delivery:'Delivery across Tashkent',aboutProduct:'About product',brand:'Brand',sample:'Sample',out:'Out of stock'}
};

const app = document.querySelector('#app');
const state = {
  lang: localStorage.getItem('abdu-lang') || 'uz',
  theme: localStorage.getItem('abdu-theme') || 'dark',
  customProducts: [], settings: structuredClone(DEFAULT_SETTINGS), configured:false,
  query:'', category:'all', sort:'recommended', adminTab:'products', adminToken:sessionStorage.getItem('abdu-admin-token') || '',
};

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function money(n){return Number(n||0).toLocaleString('ru-RU').replace(/,/g,' ') + ' so‘m';}
function phoneHref(p){return 'tel:'+String(p||'').replace(/[^+\d]/g,'');}
function tgHref(){const t=state.settings.telegram.replace(/^@/,'');return `https://t.me/${encodeURIComponent(t)}`;}
function t(){return UI[state.lang] || UI.uz;}
function categoryName(id){const c=CATEGORIES.find(x=>x.id===id);return c?c[state.lang]||c.uz:id;}
function productTitle(p){return p.title?.[state.lang] || p.title?.uz || '';}
function productDesc(p){return p.description?.[state.lang] || p.description?.uz || '';}
function visibleProducts(){const source=state.customProducts.length?state.customProducts:SAMPLE_PRODUCTS;return source.filter(p=>p.visible!==false);}
function icon(s){return `<span aria-hidden="true">${s}</span>`;}
function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;localStorage.setItem('abdu-theme',theme);}
function toggleTheme(){setTheme(state.theme==='dark'?'light':'dark');render();}
function setLang(lang){state.lang=lang;localStorage.setItem('abdu-lang',lang);render();}
function nav(path){history.pushState({},'',path);window.scrollTo({top:0,behavior:'instant'});render();}
window.addEventListener('popstate',render);

async function api(path,options={}){
  const headers={...(options.headers||{})};
  if(state.adminToken) headers.Authorization=`Bearer ${state.adminToken}`;
  const r=await fetch(path,{...options,headers});
  let data={}; try{data=await r.json();}catch{}
  if(!r.ok) throw new Error(data.error || `HTTP ${r.status}`);
  return data;
}
async function loadData(){
  try{
    const data=await api('/api/data');
    state.customProducts=Array.isArray(data.products)?data.products:[];
    state.settings={...structuredClone(DEFAULT_SETTINGS),...(data.settings||{}),about:{...DEFAULT_SETTINGS.about,...(data.settings?.about||{})}};
    state.configured=!!data.configured;
  }catch{
    const local=localStorage.getItem('abdu-local-data');
    if(local){try{const d=JSON.parse(local);state.customProducts=d.products||[];state.settings={...DEFAULT_SETTINGS,...(d.settings||{})};}catch{}}
  }
}
function persistLocal(){localStorage.setItem('abdu-local-data',JSON.stringify({products:state.customProducts,settings:state.settings}));}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2600);}

function brand(){return `<a href="/" data-nav class="brand"><img class="shop-logo" src="/assets/logo.png" alt="Abdujabbor Shop"><span class="brand-wordmark">Abdujabbor <small>Shop</small></span></a>`;}
function themeControl(){return `<div class="theme-toggle">${icon('☼')}<button class="switch ${state.theme==='dark'?'on':''}" data-theme-toggle aria-label="Theme"></button>${icon('☾')}</div>`;}
function publicHeader(){const u=t();return `
<div class="topbar"><div class="wrap"><div class="topbar-left">${icon('⌖')}<span>${esc(state.settings.location)}</span></div><div class="topbar-mid">${icon('♧')}<span>${esc(state.settings.delivery)}</span></div><div class="topbar-right"><a href="#about">${u.about}</a><a href="#contact">${u.contact}</a><select id="langTop" aria-label="Language"><option value="uz" ${state.lang==='uz'?'selected':''}>O‘zbekcha</option><option value="ru" ${state.lang==='ru'?'selected':''}>Русский</option><option value="en" ${state.lang==='en'?'selected':''}>English</option></select></div></div></div>
<header class="site-header"><div class="wrap header-row">${brand()}<form class="search-box" id="searchForm"><input id="searchInput" value="${esc(state.query)}" placeholder="${esc(u.search)}"><button>↗</button></form><div class="header-actions">${themeControl()}<a class="header-contact" href="${phoneHref(state.settings.phone1)}"><span class="icon">⌕</span><span><small>${u.question}</small><b>${esc(state.settings.phone1)}</b></span></a></div></div></header>
<nav class="category-nav wrap"><a class="catalog-label" href="/#catalog" data-nav>▦ &nbsp;${u.catalog}</a>${CATEGORIES.map(c=>`<a href="/?category=${c.id}#catalog" data-category-link="${c.id}">${esc(c[state.lang]||c.uz)}</a>`).join('')}</nav>`;}
function footer(){const u=t();return `<footer><div class="wrap footer-row">${brand()}<span>© 2026 Abdujabbor Shop</span><a href="/admin" data-nav>${u.admin} ↗</a></div></footer><nav class="mobile-nav"><a href="/#catalog" data-nav>${icon('▦')}<span>${u.catalog}</span></a><a href="/#contact" data-nav>${icon('☎')}<span>${u.contact}</span></a><a href="${tgHref()}" target="_blank">${icon('➤')}<span>Telegram</span></a></nav>`;}

function renderHome(){
  const u=t();let products=visibleProducts();
  const params=new URLSearchParams(location.search);const q=state.query.trim().toLowerCase();const cat=params.get('category')||state.category;
  if(q) products=products.filter(p=>`${productTitle(p)} ${p.brand||''} ${categoryName(p.category)}`.toLowerCase().includes(q));
  if(cat && cat!=='all') products=products.filter(p=>p.category===cat);
  if(state.sort==='low') products=[...products].sort((a,b)=>a.price-b.price);if(state.sort==='high') products=[...products].sort((a,b)=>b.price-a.price);
  const hero=visibleProducts().find(p=>p.category==='vacuum')||visibleProducts()[0]||SAMPLE_PRODUCTS[1];
  app.innerHTML=`${publicHeader()}<main class="wrap"><section class="hero"><div class="hero-copy"><p class="eyebrow">${u.heroEyebrow}</p><h1>${u.heroTitle}</h1><p>${u.heroText}</p><a href="#catalog" class="hero-button">${u.seeProducts}<span>↗</span></a></div><div class="hero-art"><img src="${esc(hero.images?.[0]||'/assets/products/vacuum.png')}" alt=""><span class="hero-label">Abdujabbor Shop</span></div></section>
<section class="service-strip"><div><span class="sicon">♧</span><span><b>${esc(state.settings.delivery)}</b><small>${esc(state.settings.deliveryNote)}</small></span></div><div><span class="sicon">⌕</span><span><b>${u.help}</b><small>${esc(state.settings.phone1)}</small></span></div><a href="${tgHref()}" target="_blank"><span class="sicon">➤</span><span><b>${u.telegram}</b><small>@${esc(state.settings.telegram.replace(/^@/,''))}</small></span><span style="margin-left:auto">↗</span></a></section>
<section id="catalog" class="catalog-section"><div class="section-heading"><div><p class="eyebrow accent-text">Abdujabbor Shop</p><h2>${u.homeNeed}<span>${products.length} ta mahsulot</span></h2></div><div class="catalog-controls"><select id="sortSelect"><option value="recommended" ${state.sort==='recommended'?'selected':''}>${u.recommended}</option><option value="low" ${state.sort==='low'?'selected':''}>${u.priceLow}</option><option value="high" ${state.sort==='high'?'selected':''}>${u.priceHigh}</option></select></div></div>
<div class="chips"><button class="${!cat||cat==='all'?'active':''}" data-chip="all">${u.all}</button>${CATEGORIES.map(c=>`<button class="${cat===c.id?'active':''}" data-chip="${c.id}">${esc(c[state.lang]||c.uz)}</button>`).join('')}</div>${state.customProducts.length?'':`<p class="demo-notice">${u.demo}</p>`}<div class="product-grid">${products.map(productCard).join('')}</div></section>
<section id="about" class="about-contact"><div><p class="eyebrow accent-text">Abdujabbor Shop</p><h2>${u.about}</h2><p>${esc(state.settings.about?.[state.lang]||state.settings.about?.uz||'')}</p></div><div id="contact" class="contact-card"><h3>${u.contactUs}</h3><div class="contact-list"><a href="${phoneHref(state.settings.phone1)}"><span class="gold">☎</span>${esc(state.settings.phone1)}</a><a href="${phoneHref(state.settings.phone2)}"><span class="gold">☎</span>${esc(state.settings.phone2)}</a><a href="${tgHref()}" target="_blank"><span class="gold">➤</span>@${esc(state.settings.telegram.replace(/^@/,''))}<span style="margin-left:auto">↗</span></a><p><span class="gold">⌖</span>${esc(state.settings.location)}</p></div></div></section></main>${footer()}`;
  bindPublic();
}
function productCard(p){const u=t();const img=p.cardImage||p.images?.[0]||'/assets/logo.png';return `<article class="product-card"><a href="/product/${encodeURIComponent(p.id)}" data-nav><div class="product-photo"><img src="${esc(img)}" alt="${esc(productTitle(p))}">${p.sample?`<span class="product-badge">${u.sample}</span><span class="photo-arrow">↗</span>`:''}</div></a><div class="product-info"><div class="product-category">${esc(categoryName(p.category))}</div><h3 class="product-title">${esc(productTitle(p))}</h3>${p.brand?`<div class="product-brand">${esc(p.brand)}</div>`:''}<div class="product-price">${money(p.price)}${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:''}</div><a href="/product/${encodeURIComponent(p.id)}" data-nav class="details-btn"><span>${u.details}</span><span>›</span></a></div></article>`;}
function bindPublic(){
  document.querySelectorAll('[data-nav]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(href?.startsWith('/')){e.preventDefault();nav(href);}}));
  document.querySelector('[data-theme-toggle]')?.addEventListener('click',toggleTheme);
  document.querySelector('#langTop')?.addEventListener('change',e=>setLang(e.target.value));
  document.querySelector('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();state.query=document.querySelector('#searchInput').value;history.replaceState({},'',`/?q=${encodeURIComponent(state.query)}#catalog`);renderHome();setTimeout(()=>document.querySelector('#catalog')?.scrollIntoView(),0);});
  document.querySelector('#sortSelect')?.addEventListener('change',e=>{state.sort=e.target.value;renderHome();setTimeout(()=>document.querySelector('#catalog')?.scrollIntoView(),0);});
  document.querySelectorAll('[data-chip]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.chip;state.category=v;const q=v==='all'?'':`?category=${v}`;history.replaceState({},'',`/${q}#catalog`);renderHome();setTimeout(()=>document.querySelector('#catalog')?.scrollIntoView(),0);}));
  document.querySelectorAll('[data-category-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();state.category=a.dataset.categoryLink;history.replaceState({},'',`/?category=${state.category}#catalog`);renderHome();setTimeout(()=>document.querySelector('#catalog')?.scrollIntoView(),0);}));
}

function renderProduct(id){const p=[...state.customProducts,...SAMPLE_PRODUCTS].find(x=>x.id===id);if(!p){nav('/');return;}const u=t();app.innerHTML=`${publicHeader()}<main class="wrap"><div class="breadcrumb"><a href="/" data-nav>${u.catalog}</a> &nbsp;›&nbsp; ${esc(productTitle(p))}</div><section class="product-detail"><div class="detail-image"><img src="${esc(p.images?.[0]||p.cardImage||'/assets/logo.png')}" alt="${esc(productTitle(p))}"></div><div class="detail-copy"><div class="category">${esc(categoryName(p.category))}</div><h1>${esc(productTitle(p))}</h1>${p.sample?`<span class="tag">${u.sample}</span>`:''}${p.brand?`<div class="brand-line">${u.brand}: ${esc(p.brand)}</div>`:''}<div class="buy-card"><div class="buy-price">${money(p.price)}</div>${p.oldPrice?`<div class="old-price" style="margin:4px 0 0">${money(p.oldPrice)}</div>`:''}<p>${u.askPrice}</p><a class="action-btn telegram" style="display:block;text-align:center" href="${tgHref()}?text=${encodeURIComponent(productTitle(p))}" target="_blank">➤ &nbsp; ${u.askTelegram}</a><a class="action-btn phone" style="display:block;text-align:center" href="${phoneHref(state.settings.phone1)}">☎ &nbsp; ${u.call}</a></div><div class="delivery-card"><b>♧ &nbsp; ${esc(state.settings.delivery)}</b><p>${esc(state.settings.deliveryNote)}</p></div><div class="detail-description"><h2>${u.aboutProduct}</h2><p>${esc(productDesc(p))}</p>${!p.inStock?`<p style="color:#c23b3b;font-weight:700">${u.out}</p>`:''}</div></div></section><h2 style="margin:20px 0 24px">O‘xshash mahsulotlar</h2><div class="product-grid">${visibleProducts().filter(x=>x.id!==p.id).slice(0,4).map(productCard).join('')}</div><div style="margin:34px 0"><a href="/#catalog" data-nav style="color:var(--primary)">← ${u.backCatalog}</a></div></main>${footer()}`;bindPublic();}

function adminHeader(){return `<header class="admin-header"><div class="wrap"><div class="admin-left">${brand()}<span class="admin-title">Admin panel</span></div><div class="admin-actions">${themeControl()}<button class="ghost-btn" id="logoutBtn">Chiqish</button></div></div></header>`;}
function renderAdmin(){if(!state.adminToken){renderLogin();return;}app.innerHTML=`<div class="admin-shell">${adminHeader()}<main class="wrap admin-main"><a href="/" data-nav class="link-back">← &nbsp; Katalogni ochish</a><div class="admin-tabs"><button class="${state.adminTab==='products'?'active':''}" data-admin-tab="products">Mahsulotlar</button><button class="${state.adminTab==='settings'?'active':''}" data-admin-tab="settings">Aloqa sozlamalari</button></div><div id="adminContent">${state.adminTab==='products'?adminProductsHtml():adminSettingsHtml()}</div></main></div>`;bindAdminBase();if(state.adminTab==='products')bindAdminProducts();else bindAdminSettings();}
function bindAdminBase(){document.querySelectorAll('[data-nav]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();nav(a.getAttribute('href'));}));document.querySelector('[data-theme-toggle]')?.addEventListener('click',toggleTheme);document.querySelector('#logoutBtn')?.addEventListener('click',()=>{state.adminToken='';sessionStorage.removeItem('abdu-admin-token');renderAdmin();});document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{state.adminTab=b.dataset.adminTab;renderAdmin();}));}
function renderLogin(){app.innerHTML=`<div class="login-wrap"><form class="login-card" id="loginForm"><img class="shop-logo" src="/assets/logo.png" alt=""><h1>Admin panel</h1><p>Mahsulotlar va aloqa sozlamalarini boshqarish uchun kiring.</p><div class="field" style="text-align:left;margin-top:24px"><label>Admin paroli</label><input id="adminPassword" type="password" autocomplete="current-password" required></div><div class="login-error" id="loginError"></div><button class="primary-btn" style="width:100%">Kirish</button><p style="margin-top:18px"><a href="/" data-nav style="color:var(--primary)">← Katalogga qaytish</a></p></form></div>`;document.querySelector('[data-nav]').addEventListener('click',e=>{e.preventDefault();nav('/');});document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const err=document.querySelector('#loginError');err.textContent='';try{const data=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.querySelector('#adminPassword').value})});state.adminToken=data.token;sessionStorage.setItem('abdu-admin-token',data.token);renderAdmin();}catch(ex){err.textContent=ex.message.includes('not configured')?'Cloudflare secrets hali sozlanmagan. README dagi ADMIN_PASSWORD va SESSION_SECRET ni qo‘shing.':'Parol noto‘g‘ri yoki serverga ulanib bo‘lmadi.';}});}
function adminProductsHtml(){return `<div class="admin-heading"><div><h1>Mahsulotlar</h1><p>Rasmlar, narxlar va mahsulot ma’lumotlarini shu yerdan boshqaring.</p></div><button class="primary-btn" id="addProductBtn">＋ &nbsp; Mahsulot qo‘shish</button></div>${state.customProducts.length?`<div class="admin-list">${state.customProducts.map(p=>`<div class="admin-product-row"><img src="${esc(p.images?.[0]||'/assets/logo.png')}" alt=""><div><b>${esc(p.title?.uz||'Nomsiz')}</b><div class="muted" style="font-size:12px">${esc(p.brand||'')} · ${esc(categoryName(p.category))} · ${money(p.price)}</div></div><div class="row-actions"><button class="ghost-btn" data-edit="${esc(p.id)}">Tahrirlash</button><button class="danger-btn" data-delete="${esc(p.id)}">O‘chirish</button></div></div>`).join('')}</div>`:`<div class="empty-state"><div><div class="boxicon">⬡</div><h2>Birinchi mahsulotingizni qo‘shing</h2><p>Hozir katalogda namuna mahsulotlar bor. Birinchi mahsulot saqlangach, katalogda o‘zingiz kiritgan mahsulotlar ko‘rinadi.</p><button class="primary-btn" id="addProductBtn2">＋ &nbsp; Mahsulot qo‘shish</button></div></div>`}`;}
function bindAdminProducts(){document.querySelector('#addProductBtn')?.addEventListener('click',()=>renderProductForm());document.querySelector('#addProductBtn2')?.addEventListener('click',()=>renderProductForm());document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>renderProductForm(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Mahsulotni o‘chirasizmi?'))return;try{await api(`/api/products/${encodeURIComponent(b.dataset.delete)}`,{method:'DELETE'});state.customProducts=state.customProducts.filter(p=>p.id!==b.dataset.delete);persistLocal();toast('Mahsulot o‘chirildi');renderAdmin();}catch(ex){alert(ex.message);}}));}
function adminSettingsHtml(){const s=state.settings;return `<div class="admin-heading"><div><h1>Aloqa sozlamalari</h1><p>Telefon, Telegram va do‘kon matnlarini shu yerdan o‘zgartiring.</p></div></div><form class="form-card settings-card" id="settingsForm"><div class="two-cols"><div class="field"><label>Asosiy telefon</label><input name="phone1" value="${esc(s.phone1)}"></div><div class="field"><label>Ikkinchi telefon</label><input name="phone2" value="${esc(s.phone2)}"></div></div><div class="field"><label>Telegram username</label><input name="telegram" value="${esc(s.telegram)}" placeholder="Abdujabbor_shop"></div><div class="field"><label>Joylashuv</label><input name="location" value="${esc(s.location)}"></div><div class="field"><label>Yetkazib berish sarlavhasi</label><input name="delivery" value="${esc(s.delivery)}"></div><div class="field"><label>Yetkazib berish izohi</label><textarea name="deliveryNote">${esc(s.deliveryNote)}</textarea></div><div class="form-lang"><h3>O‘zbekcha</h3><div class="field"><label>Biz haqimizda</label><textarea name="about_uz">${esc(s.about?.uz||'')}</textarea></div></div><div class="form-lang"><h3>Русский</h3><div class="field"><label>О нас</label><textarea name="about_ru">${esc(s.about?.ru||'')}</textarea></div></div><div class="form-lang"><h3>English</h3><div class="field"><label>About us</label><textarea name="about_en">${esc(s.about?.en||'')}</textarea></div></div><div class="form-footer"><button class="save-btn">💾 &nbsp; Saqlash</button></div></form>`;}
function bindAdminSettings(){document.querySelector('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next={phone1:fd.get('phone1'),phone2:fd.get('phone2'),telegram:String(fd.get('telegram')||'').replace(/^@/,''),location:fd.get('location'),delivery:fd.get('delivery'),deliveryNote:fd.get('deliveryNote'),about:{uz:fd.get('about_uz'),ru:fd.get('about_ru'),en:fd.get('about_en')}};try{const data=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});state.settings=data.settings||next;persistLocal();toast('Sozlamalar saqlandi');}catch(ex){alert(ex.message);}});}

let formFiles=[];let formImages=[];
function renderProductForm(id=''){const p=state.customProducts.find(x=>x.id===id)||null;formFiles=[];formImages=[...(p?.images||[])];app.innerHTML=`<div class="admin-shell">${adminHeader()}<main class="wrap admin-main"><a href="/admin" data-nav class="link-back">← &nbsp; Mahsulotlarga qaytish</a><div class="admin-tabs"><button class="active">Mahsulotlar</button><button data-settings-shortcut>Aloqa sozlamalari</button></div><div class="admin-heading"><div><h1>${p?'Mahsulotni tahrirlash':'Yangi mahsulot'}</h1><p>Rasmlar, narxlar va mahsulot ma’lumotlarini shu yerdan boshqaring.</p></div></div>${productFormHtml(p)}</main></div>`;bindAdminBase();document.querySelector('[data-settings-shortcut]')?.addEventListener('click',()=>{state.adminTab='settings';nav('/admin');});bindProductForm(p);}
function productFormHtml(p){const g=(o,k,d='')=>esc(o?.[k]??d);return `<form class="form-card" id="productForm"><div class="form-grid"><div class="form-section"><h2>Mahsulot rasmlari</h2><p>JPG, PNG yoki WebP · har biri 5 MB gacha · 6 tagacha. Birinchi rasm katalogda chiqadi.</p><div class="upload-preview" id="uploadPreview"></div><div class="upload-zone"><label><input type="file" id="imageInput" accept="image/jpeg,image/png,image/webp" multiple><span><b style="font-size:28px">▧＋</b><b>Rasm yuklash</b><small>Telefon yoki kompyuterdan tanlang</small></span></label></div><div class="two-cols"><div class="field"><label>Narx (so‘m)</label><input name="price" type="number" min="0" value="${g(p,'price','0')}" required></div><div class="field"><label>Eski narx (ixtiyoriy)</label><input name="oldPrice" type="number" min="0" value="${g(p,'oldPrice','')}"></div></div><div class="field"><label>Brend</label><input name="brand" value="${g(p,'brand','')}" placeholder="Masalan: Artel, Philips, Tefal"></div><div class="field"><label>Kategoriya</label><select name="category">${CATEGORIES.map(c=>`<option value="${c.id}" ${p?.category===c.id?'selected':''}>${c.uz}</option>`).join('')}</select></div><label class="toggle-line">Sotuvda mavjud<input type="checkbox" name="inStock" ${p?.inStock!==false?'checked':''} hidden><span class="toggle-box ${p?.inStock!==false?'on':''}" data-toggle-for="inStock"></span></label><label class="toggle-line">Katalogda ko‘rsatish<input type="checkbox" name="visible" ${p?.visible!==false?'checked':''} hidden><span class="toggle-box ${p?.visible!==false?'on':''}" data-toggle-for="visible"></span></label></div><div class="form-section"><h2>Nomi va tavsifi</h2><p>Har bir til uchun matn kiriting.</p>${['uz','ru','en'].map((l,i)=>`<div class="form-lang"><h3>${l==='uz'?'O‘zbekcha':l==='ru'?'Русский':'English'}</h3><div class="field"><label>Mahsulot nomi</label><input name="title_${l}" value="${esc(p?.title?.[l]||'')}" ${i===0?'required':''}></div><div class="field"><label>Tavsif</label><textarea name="description_${l}">${esc(p?.description?.[l]||'')}</textarea></div></div>`).join('')}</div></div><div class="form-footer"><button type="button" class="secondary-btn" id="cancelProduct">Bekor qilish</button><button class="save-btn">💾 &nbsp; Saqlash</button></div></form>`;}
function bindProductForm(p){renderUploadPreview();document.querySelector('#cancelProduct').addEventListener('click',()=>nav('/admin'));document.querySelectorAll('[data-toggle-for]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();const n=x.dataset.toggleFor;const cb=document.querySelector(`[name="${n}"]`);cb.checked=!cb.checked;x.classList.toggle('on',cb.checked);}));document.querySelector('#imageInput').addEventListener('change',e=>{const files=[...e.target.files].filter(f=>f.size<=5*1024*1024).slice(0,Math.max(0,6-formImages.length-formFiles.length));formFiles.push(...files);renderUploadPreview();e.target.value='';});document.querySelector('#productForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const btn=e.currentTarget.querySelector('.save-btn');btn.disabled=true;btn.textContent='Saqlanmoqda...';try{const uploaded=[];for(const file of formFiles){const f=new FormData();f.append('file',file);const r=await api('/api/upload',{method:'POST',body:f});uploaded.push(r.url);}const product={id:p?.id||`p-${Date.now()}`,price:Number(fd.get('price')||0),oldPrice:Number(fd.get('oldPrice')||0),brand:String(fd.get('brand')||'').trim(),category:String(fd.get('category')||'kitchen'),inStock:fd.get('inStock')==='on',visible:fd.get('visible')==='on',images:[...formImages,...uploaded].slice(0,6),title:{uz:String(fd.get('title_uz')||'').trim(),ru:String(fd.get('title_ru')||'').trim(),en:String(fd.get('title_en')||'').trim()},description:{uz:String(fd.get('description_uz')||'').trim(),ru:String(fd.get('description_ru')||'').trim(),en:String(fd.get('description_en')||'').trim()}};const data=await api(p?`/api/products/${encodeURIComponent(p.id)}`:'/api/products',{method:p?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(product)});const saved=data.product||product;if(p)state.customProducts=state.customProducts.map(x=>x.id===p.id?saved:x);else state.customProducts.push(saved);persistLocal();toast('Mahsulot saqlandi');nav('/admin');}catch(ex){alert(ex.message);btn.disabled=false;btn.textContent='💾  Saqlash';}});}
function renderUploadPreview(){const el=document.querySelector('#uploadPreview');if(!el)return;const local=formFiles.map((f,i)=>({src:URL.createObjectURL(f),type:'file',i}));el.innerHTML=[...formImages.map((src,i)=>({src,type:'url',i})),...local].map(x=>`<div class="thumb"><img src="${esc(x.src)}"><button type="button" data-rm-type="${x.type}" data-rm-index="${x.i}">×</button></div>`).join('');el.querySelectorAll('[data-rm-type]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.rmIndex);if(b.dataset.rmType==='url')formImages.splice(i,1);else formFiles.splice(i,1);renderUploadPreview();}));}

function route(){const q=new URLSearchParams(location.search).get('q');if(q!==null)state.query=q;const path=location.pathname;if(path==='/admin')return renderAdmin();if(path.startsWith('/product/'))return renderProduct(decodeURIComponent(path.split('/').pop()));return renderHome();}
function render(){route();}
setTheme(state.theme);
await loadData();
route();
