'use client';
import {useEffect,useState} from 'react';
import {Phone,Send,Save} from 'lucide-react';
import {toast} from 'sonner';
import type {ShopSettings} from '@/lib/settings';
export default function SettingsPanel(){const [form,setForm]=useState<ShopSettings|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function load(){setError('');try{const r=await fetch('/api/admin/settings',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as {settings:ShopSettings};setForm(d.settings)}catch{setError('Aloqa ma’lumotlarini yuklab bo‘lmadi.')}}useEffect(()=>{load()},[]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json() as {settings:ShopSettings;error?:string};if(!r.ok)throw Error(d.error||'Saqlanmadi');setForm(d.settings);toast.success('Aloqa ma’lumotlari saqlandi. Saytdagi havolalar yangilandi.')}catch(e){toast.error(e instanceof Error?e.message:'Saqlanmadi')}finally{setBusy(false)}}
return <section className="settings-section"><h1>Aloqa sozlamalari</h1><p className="muted">Raqamlar va Telegram havolasi saytning barcha bo‘limlarida yangilanadi.</p>{error?<div className="empty" role="alert"><p>{error}</p><button className="primary" onClick={load}>Qayta urinish</button></div>:!form?<p className="empty" role="status">Yuklanmoqda...</p>:<form className="editor settings-editor" onSubmit={save}><fieldset disabled={busy}><h2><Phone size={20}/> Telefon raqamlari</h2><label>Asosiy telefon raqami<input type="tel" required maxLength={35} autoComplete="tel" placeholder="+998 97 400 77 53" value={form.phonePrimary} onChange={e=>setForm({...form,phonePrimary:e.target.value})}/></label><label>Ikkinchi raqam (ixtiyoriy)<input type="tel" maxLength={35} placeholder="+998 97 407 77 53" value={form.phoneSecondary} onChange={e=>setForm({...form,phoneSecondary:e.target.value})}/></label><h2 className="settings-subtitle"><Send size={20}/> Telegram</h2><label>Telegram kanal yoki profil havolasi<input type="url" required maxLength={100} placeholder="https://t.me/Abdujabbor_shop" value={form.telegram} onChange={e=>setForm({...form,telegram:e.target.value})}/></label><p className="muted field-hint">Masalan: https://t.me/Abdujabbor_shop</p></fieldset><div className="editor-actions"><button className="primary" disabled={busy}><Save size={18}/>{busy?'Saqlanmoqda...':'Saqlash'}</button></div></form>}</section>}
